// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YoklamaFisi.Data;

#nullable disable

namespace YoklamaFisi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251018211939_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YoklamaFisi.Models.Entities.Ders", b =>
                {
                    b.Property<int>("DersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisaAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SinifId")
                        .HasColumnType("int");

                    b.HasKey("DersId");

                    b.HasIndex("SinifId");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("YoklamaFisi.Models.Entities.DersProgrami", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("DersSaati")
                        .HasColumnType("int");

                    b.Property<int>("Gun")
                        .HasColumnType("int");

                    b.Property<int?>("Ogretmen1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Ogretmen2Id")
                        .HasColumnType("int");

                    b.Property<int?>("Ogretmen3Id")
                        .HasColumnType("int");

                    b.Property<int>("SinifId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.HasIndex("Ogretmen1Id");

                    b.HasIndex("Ogretmen2Id");

                    b.HasIndex("Ogretmen3Id");

                    b.HasIndex("SinifId");

                    b.ToTable("DersProgramlari");
                });

            modelBuilder.Entity("YoklamaFisi.Models.Entities.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numara")
                        .HasColumnType("int");

                    b.Property<int>("SinifId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SinifId");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("YoklamaFisi.Models.Entities.Ogretmen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ogretmenler");
                });

            modelBuilder.Entity("YoklamaFisi.Models.Entities.Sinif", b =>
                {
                    b.Property<int>("SinifId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinifId"));

                    b.Property<string>("SinifAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SinifId");

                    b.ToTable("Siniflar");
                });

            modelBuilder.Entity("YoklamaFisi.Models.Entities.YoklamaKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DersSaati")
                        .HasColumnType("int");

                    b.Property<bool>("GeldiMi")
                        .HasColumnType("bit");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.ToTable("YoklamaKayitlari");
                });

            modelBuilder.Entity("YoklamaFisi.Models.Entities.Ders", b =>
                {
                    b.HasOne("YoklamaFisi.Models.Entities.Sinif", "Sinif")
                        .WithMany("Dersler")
                        .HasForeignKey("SinifId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("YoklamaFisi.Models.Entities.DersProgrami", b =>
                {
                    b.HasOne("YoklamaFisi.Models.Entities.Ders", "Ders")
                        .WithMany("DersProgramlari")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YoklamaFisi.Models.Entities.Ogretmen", "Ogretmen1")
                        .WithMany()
                        .HasForeignKey("Ogretmen1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("YoklamaFisi.Models.Entities.Ogretmen", "Ogretmen2")
                        .WithMany()
                        .HasForeignKey("Ogretmen2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("YoklamaFisi.Models.Entities.Ogretmen", "Ogretmen3")
                        .WithMany()
                        .HasForeignKey("Ogretmen3Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("YoklamaFisi.Models.Entities.Sinif", "Sinif")
                        .WithMany()
                        .HasForeignKey("SinifId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogretmen1");

                    b.Navigation("Ogretmen2");

                    b.Navigation("Ogretmen3");

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("YoklamaFisi.Models.Entities.Ogrenci", b =>
                {
                    b.HasOne("YoklamaFisi.Models.Entities.Sinif", "Sinif")
                        .WithMany()
                        .HasForeignKey("SinifId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("YoklamaFisi.Models.Entities.YoklamaKaydi", b =>
                {
                    b.HasOne("YoklamaFisi.Models.Entities.Ogrenci", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("YoklamaFisi.Models.Entities.Ders", b =>
                {
                    b.Navigation("DersProgramlari");
                });

            modelBuilder.Entity("YoklamaFisi.Models.Entities.Sinif", b =>
                {
                    b.Navigation("Dersler");
                });
#pragma warning restore 612, 618
        }
    }
}
